// Command genpins writes the versions docker-compose.matrix.yml pins as Go, so the health
// screen compares running versions with what Compose deploys. `go generate ./internal/health`
// runs it; TestPinsMatchCompose fails when the two drift.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"regexp"
	"strings"

	"gopkg.in/yaml.v3"
)

var services = []string{"element", "mas", "postgres", "synapse"}

func main() {
	compose := flag.String("compose", "", "path to docker-compose.matrix.yml")
	out := flag.String("out", "", "Go file to write")
	flag.Parse()
	src, err := os.ReadFile(*compose)
	if err != nil {
		log.Fatal(err)
	}
	code, err := render(src)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, code, 0o644); err != nil {
		log.Fatal(err)
	}
}

// render returns pins.go for compose: each service's image tag without a leading "v" or a
// "-variant" suffix ("v1.162.0" → "1.162.0", "17.6-alpine" → "17.6").
func render(compose []byte) ([]byte, error) {
	var doc struct {
		Services map[string]struct {
			Image string `yaml:"image"`
		} `yaml:"services"`
	}
	if err := yaml.Unmarshal(compose, &doc); err != nil {
		return nil, err
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by genpins from docker-compose.matrix.yml; DO NOT EDIT.\n\npackage health\n\n")
	b.WriteString("// Pins are the versions docker-compose.matrix.yml deploys, by Compose service.\nvar Pins = map[string]string{\n")
	for _, name := range services {
		v, err := tagVersion(doc.Services[name].Image)
		if err != nil {
			return nil, fmt.Errorf("service %s: %w", name, err)
		}
		fmt.Fprintf(&b, "\t%q: %q,\n", name, v)
	}
	b.WriteString("}\n")
	return format.Source(b.Bytes())
}

var release = regexp.MustCompile(`^[0-9]+(\.[0-9]+)+$`)

func tagVersion(image string) (string, error) {
	ref, _, _ := strings.Cut(image, "@")
	i := strings.LastIndex(ref, ":")
	if i < 0 || strings.Contains(ref[i:], "/") {
		return "", fmt.Errorf("image %q has no tag", image)
	}
	v, _, _ := strings.Cut(strings.TrimPrefix(ref[i+1:], "v"), "-")
	if !release.MatchString(v) {
		return "", fmt.Errorf("image %q: tag is not a release version", image)
	}
	return v, nil
}
